package com.mathan.erp.voucher;

import com.fasterxml.jackson.databind.JsonNode;
import com.mathan.erp.api.ApiException;
import com.mathan.erp.security.UserPrincipal;
import com.mathan.erp.tenant.TenantService;
import com.mathan.erp.validation.ReferenceIntegrityService;
import java.math.BigDecimal;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class VoucherService {
  private final JdbcClient db; private final TenantService tenants; private final ReferenceIntegrityService refs; private final VoucherNumberService numbers; private final VoucherValidationService validation;
  public VoucherService(JdbcClient db,TenantService tenants,ReferenceIntegrityService refs,VoucherNumberService numbers,VoucherValidationService validation){this.db=db;this.tenants=tenants;this.refs=refs;this.numbers=numbers;this.validation=validation;}
  public List<Map<String,Object>> list(UserPrincipal user,String header){UUID b=tenants.require(user,header,"reports").businessId();return db.sql("select id,type,voucher_date as date,number,status,narration,actor_id,currency_id,exchange_rate,party_id,created_at,updated_at from voucher where business_id=:b order by voucher_date desc,created_at desc").param("b",b).query((rs,n)->voucherMap(rs,b)).list();}
  @Transactional public Map<String,Object> create(UserPrincipal user,String header,JsonNode body){var tenant=tenants.require(user,header,"transactions");return save(null,user,tenant,body);}
  @Transactional public Map<String,Object> update(UUID id,UserPrincipal user,String header,JsonNode body){var tenant=tenants.require(user,header,"transactions");assertOpen(id,tenant.businessId());rollbackStock(id,tenant.businessId());db.sql("delete from voucher_line where voucher_id=:id").param("id",id).update();db.sql("delete from stock_movement where voucher_id=:id").param("id",id).update();return save(id,user,tenant,body);}
  @Transactional public void cancel(UUID id,UserPrincipal user,String header){var t=tenants.require(user,header,"transactions");assertOpen(id,t.businessId());rollbackStock(id,t.businessId());int n=db.sql("update voucher set status='Cancelled',updated_at=now(),version=version+1 where id=:id and business_id=:b").param("id",id).param("b",t.businessId()).update();if(n==0)notFound();audit(t.businessId(),user.id(),"Voucher cancelled",id);}
  private Map<String,Object> save(UUID existing,UserPrincipal user,TenantService.Membership t,JsonNode body){
    var validated=validation.validateForPost(t.businessId(),body);String type=validated.type();LocalDate date=validated.date();JsonNode lines=body.path("lines"), stock=body.path("stockLines");
    UUID currency=uuid(body,"currencyId"),party=uuidOrNull(body,"partyId");refs.requireCurrency(t.businessId(),currency,true);if(party!=null)refs.requireParty(t.businessId(),party,true);BigDecimal rate=validated.exchangeRate();
    UUID id=existing==null?UUID.randomUUID():existing;String number=existing==null?numbers.next(t.businessId(),type):null;Map<String,BigDecimal> settlements=new HashMap<>();
    if(existing==null)db.sql("insert into voucher(id,business_id,type,voucher_date,number,status,narration,actor_id,currency_id,exchange_rate,party_id) values(:id,:b,:t,:d,:n,'Posted',:x,:a,:c,:r,:p)").param("id",id).param("b",t.businessId()).param("t",type).param("d",date).param("n",number).param("x",body.path("narration").asText("")).param("a",user.id()).param("c",currency).param("r",rate).param("p",party).update();
    else db.sql("update voucher set type=:t,voucher_date=:d,narration=:x,currency_id=:c,exchange_rate=:r,party_id=:p,updated_at=now(),version=version+1 where id=:id and business_id=:b").param("t",type).param("d",date).param("x",body.path("narration").asText("")).param("c",currency).param("r",rate).param("p",party).param("id",id).param("b",t.businessId()).update();
    if(lines.isArray())for(JsonNode l:lines){UUID ledger=uuid(l,"ledgerId"),costCenter=uuidOrNull(l,"costCenterId");refs.requireLedger(t.businessId(),ledger,true);if(costCenter!=null)refs.requireCostCenter(t.businessId(),costCenter,true);UUID line=UUID.randomUUID();db.sql("insert into voucher_line(id,business_id,voucher_id,ledger_id,debit,credit,txn_debit,txn_credit,cost_center_id) values(:id,:b,:v,:l,:d,:c,:td,:tc,:cc)").param("id",line).param("b",t.businessId()).param("v",id).param("l",ledger).param("d",decimal(l,"debit",BigDecimal.ZERO)).param("c",decimal(l,"credit",BigDecimal.ZERO)).param("td",decimalOrNull(l,"txnDebit")).param("tc",decimalOrNull(l,"txnCredit")).param("cc",costCenter).update();if(l.path("billDetails").isArray())for(JsonNode bill:l.path("billDetails")){String billType=required(bill,"type");BigDecimal amount=decimal(bill,"amount",BigDecimal.ZERO);validateBillAllocation(t.businessId(),ledger,bill,billType,amount,settlements);db.sql("insert into bill_allocation(voucher_line_id,bill_no,amount,type,due_date) values(:v,:n,:a,:t,:d)").param("v",line).param("n",required(bill,"billNo")).param("a",amount).param("t",billType).param("d",optionalDate(bill,"dueDate")).update();}}
    BigDecimal stockCost=BigDecimal.ZERO;if(stock.isArray()){Map<String,BigDecimal> transferCosts=new HashMap<>();for(JsonNode s:stock)stockCost=stockCost.add(applyStock(id,t,s,"StockTransfer".equals(type)?transferCosts:null));}postCostOfSales(t.businessId(),id,type,stockCost,rate);
    audit(t.businessId(),user.id(),existing==null?"Voucher posted":"Voucher updated",id);return get(id,t.businessId());
  }
  private BigDecimal applyStock(UUID voucher,TenantService.Membership t,JsonNode s,Map<String,BigDecimal> transferCosts){UUID product=uuid(s,"productId"),warehouse=uuid(s,"warehouseId"),unit=uuid(s,"unitId");refs.requireProduct(t.businessId(),product,true);refs.requireWarehouse(t.businessId(),warehouse,true);refs.requireUnit(t.businessId(),unit,true);BigDecimal qty=decimal(s,"quantity",BigDecimal.ZERO),rate=decimal(s,"rate",BigDecimal.ZERO);if(qty.signum()==0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_STOCK_QUANTITY","Stock quantity cannot be zero");if(rate.signum()<0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_AMOUNT","Stock rate cannot be negative");if(transferCosts!=null&&qty.signum()>0&&rate.signum()==0)rate=transferCosts.getOrDefault(product.toString(),rate);var current=db.sql("select quantity,inventory_value from stock_balance where business_id=:b and product_id=:p and warehouse_id=:w for update").param("b",t.businessId()).param("p",product).param("w",warehouse).query((rs,n)->new StockCosting.Balance(rs.getBigDecimal("quantity"),rs.getBigDecimal("inventory_value"))).optional().orElse(new StockCosting.Balance(BigDecimal.ZERO,BigDecimal.ZERO));var movement=StockCosting.apply(current,qty,rate,t.allowNegativeInventory());if(movement==null)throw new ApiException(HttpStatus.CONFLICT,"INSUFFICIENT_STOCK","Insufficient stock for product "+product);var next=movement.balance();db.sql("insert into stock_balance(business_id,product_id,warehouse_id,quantity,inventory_value,average_cost,costing_basis) values(:b,:p,:w,:q,:iv,:ac,'MOVING_AVERAGE_COST') on conflict(business_id,product_id,warehouse_id) do update set quantity=:q,inventory_value=:iv,average_cost=:ac,costing_basis='MOVING_AVERAGE_COST',version=stock_balance.version+1").param("b",t.businessId()).param("p",product).param("w",warehouse).param("q",next.quantity()).param("iv",next.inventoryValue()).param("ac",StockCosting.averageCost(next)).update();db.sql("insert into stock_movement(business_id,voucher_id,product_id,warehouse_id,unit_id,quantity,rate,cost_value) values(:b,:v,:p,:w,:u,:q,:r,:cv)").param("b",t.businessId()).param("v",voucher).param("p",product).param("w",warehouse).param("u",unit).param("q",qty).param("r",rate).param("cv",movement.costValue()).update();if(transferCosts!=null&&qty.signum()<0)transferCosts.put(product.toString(),movement.costValue().abs().divide(qty.abs(),12,java.math.RoundingMode.HALF_UP));return movement.costValue();}
  private void postCostOfSales(UUID business,UUID voucher,String type,BigDecimal stockCost,BigDecimal exchangeRate){if((!"Sale".equals(type)&&!"SalesReturn".equals(type))||stockCost.signum()==0)return;UUID cogs=db.sql("select id from ledger where business_id=:b and account_code='3100' and active").param("b",business).query(UUID.class).optional().orElseThrow(()->new ApiException(HttpStatus.CONFLICT,"COGS_LEDGER_MISSING","Cost of Sales account 3100 is required for sale postings"));UUID inventory=db.sql("select id from ledger where business_id=:b and account_code='1400' and active").param("b",business).query(UUID.class).optional().orElseThrow(()->new ApiException(HttpStatus.CONFLICT,"INVENTORY_LEDGER_MISSING","Inventory Control account 1400 is required for sale postings"));if(db.sql("select count(*) from voucher_line where voucher_id=:v and ledger_id in (:c,:i)").param("v",voucher).param("c",cogs).param("i",inventory).query(Long.class).single()>0)throw new ApiException(HttpStatus.BAD_REQUEST,"COGS_LINES_SERVER_OWNED","Cost of sales lines are generated by the backend");BigDecimal amount=stockCost.abs(),txn=amount.divide(exchangeRate,4,java.math.RoundingMode.HALF_UP);boolean sale="Sale".equals(type);db.sql("insert into voucher_line(id,business_id,voucher_id,ledger_id,debit,credit,txn_debit,txn_credit) values(:id,:b,:v,:l,:d,:c,:td,:tc)").param("id",UUID.randomUUID()).param("b",business).param("v",voucher).param("l",sale?cogs:inventory).param("d",sale?amount:BigDecimal.ZERO).param("c",sale?BigDecimal.ZERO:amount).param("td",sale?txn:BigDecimal.ZERO).param("tc",sale?BigDecimal.ZERO:txn).update();db.sql("insert into voucher_line(id,business_id,voucher_id,ledger_id,debit,credit,txn_debit,txn_credit) values(:id,:b,:v,:l,:d,:c,:td,:tc)").param("id",UUID.randomUUID()).param("b",business).param("v",voucher).param("l",sale?inventory:cogs).param("d",sale?BigDecimal.ZERO:amount).param("c",sale?amount:BigDecimal.ZERO).param("td",sale?BigDecimal.ZERO:txn).param("tc",sale?txn:BigDecimal.ZERO).update();}
  private void rollbackStock(UUID voucher,UUID business){var rows=db.sql("select product_id,warehouse_id,sum(quantity) quantity,sum(cost_value) cost_value from stock_movement where voucher_id=:v group by product_id,warehouse_id").param("v",voucher).query((rs,n)->Map.of("p",rs.getObject(1,UUID.class),"w",rs.getObject(2,UUID.class),"q",rs.getBigDecimal(3),"cv",rs.getBigDecimal(4))).list();for(var x:rows){var current=db.sql("select quantity,inventory_value from stock_balance where business_id=:b and product_id=:p and warehouse_id=:w for update").param("b",business).param("p",x.get("p")).param("w",x.get("w")).query((rs,n)->new StockCosting.Balance(rs.getBigDecimal("quantity"),rs.getBigDecimal("inventory_value"))).single();var next=new StockCosting.Balance(current.quantity().subtract((BigDecimal)x.get("q")),current.inventoryValue().subtract((BigDecimal)x.get("cv")));db.sql("update stock_balance set quantity=:q,inventory_value=:iv,average_cost=:ac,costing_basis='MOVING_AVERAGE_COST',version=version+1 where business_id=:b and product_id=:p and warehouse_id=:w").param("q",next.quantity()).param("iv",next.inventoryValue()).param("ac",StockCosting.averageCost(next)).param("b",business).param("p",x.get("p")).param("w",x.get("w")).update();}}
  private void assertPeriodOpen(UUID business,LocalDate date){Boolean closed=db.sql("select closed from period where business_id=:b and :d between start_date and end_date order by start_date desc limit 1").param("b",business).param("d",date).query(Boolean.class).optional().orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"PERIOD_REQUIRED","An accounting period must cover the voucher date"));if(closed)throw new ApiException(HttpStatus.CONFLICT,"PERIOD_CLOSED","The accounting period is closed");}
  private void assertOpen(UUID id,UUID b){var row=db.sql("select voucher_date,status from voucher where id=:id and business_id=:b for update").param("id",id).param("b",b).query((rs,n)->Map.of("date",rs.getObject(1,LocalDate.class),"status",rs.getString(2))).optional().orElseThrow(this::nf);if(!"Posted".equals(row.get("status"))){String code="Cancelled".equals(row.get("status"))?"VOUCHER_ALREADY_CANCELLED":"VOUCHER_NOT_OPEN";throw new ApiException(HttpStatus.CONFLICT,code,"Only posted vouchers can be edited or cancelled");}assertPeriodOpen(b,(LocalDate)row.get("date"));}
  private Map<String,Object> get(UUID id,UUID b){return db.sql("select id,type,voucher_date as date,number,status,narration,actor_id,currency_id,exchange_rate,party_id,created_at,updated_at from voucher where id=:id and business_id=:b").param("id",id).param("b",b).query((rs,n)->voucherMap(rs,b)).optional().orElseThrow(this::nf);}
  private Map<String,Object> voucherMap(java.sql.ResultSet rs,UUID b)throws java.sql.SQLException{UUID id=rs.getObject("id",UUID.class);var m=new LinkedHashMap<String,Object>();m.put("id",id);m.put("businessId",b);m.put("type",rs.getString("type"));m.put("date",rs.getObject("date",LocalDate.class).toString());m.put("number",rs.getString("number"));m.put("status",rs.getString("status"));m.put("narration",rs.getString("narration"));m.put("actorId",rs.getObject("actor_id",UUID.class));m.put("currencyId",rs.getObject("currency_id",UUID.class));m.put("exchangeRate",rs.getBigDecimal("exchange_rate"));m.put("partyId",rs.getObject("party_id",UUID.class));m.put("createdAt",rs.getTimestamp("created_at").toInstant());m.put("updatedAt",rs.getTimestamp("updated_at").toInstant());m.put("lines",db.sql("select id,ledger_id,debit,credit,txn_debit,txn_credit,cost_center_id from voucher_line where voucher_id=:v").param("v",id).query((x,n)->{var line=new LinkedHashMap<String,Object>();UUID lineId=x.getObject("id",UUID.class);line.put("ledgerId",x.getObject("ledger_id",UUID.class));line.put("debit",x.getBigDecimal("debit"));line.put("credit",x.getBigDecimal("credit"));line.put("txnDebit",x.getBigDecimal("txn_debit"));line.put("txnCredit",x.getBigDecimal("txn_credit"));line.put("costCenterId",x.getObject("cost_center_id",UUID.class));line.put("billDetails",db.sql("select bill_no,amount,type,due_date from bill_allocation where voucher_line_id=:v order by id").param("v",lineId).query((y,k)->{var bill=new LinkedHashMap<String,Object>();bill.put("billNo",y.getString("bill_no"));bill.put("amount",y.getBigDecimal("amount"));bill.put("type",y.getString("type"));bill.put("dueDate",y.getObject("due_date",LocalDate.class));return bill;}).list());return line;}).list());m.put("stockLines",db.sql("select product_id,warehouse_id,unit_id,quantity,rate from stock_movement where voucher_id=:v").param("v",id).query((x,n)->Map.of("productId",x.getObject(1,UUID.class),"warehouseId",x.getObject(2,UUID.class),"unitId",x.getObject(3,UUID.class),"quantity",x.getBigDecimal(4),"rate",x.getBigDecimal(5))).list());return m;}
  private void audit(UUID b,UUID a,String action,UUID id){db.sql("insert into audit_log(business_id,actor_id,action,entity_type,entity_id,details) values(:b,:a,:x,'voucher',:id,:x)").param("b",b).param("a",a).param("x",action).param("id",id).update();}
  private void validateBillAllocation(UUID business,UUID ledger,JsonNode bill,String type,BigDecimal amount,Map<String,BigDecimal> settlements){if(amount.signum()<=0)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_BILL_AMOUNT","Bill allocation amount must be positive");if(!Set.of("New Ref","Against Ref").contains(type))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_BILL_TYPE","Bill type must be New Ref or Against Ref");if("Against Ref".equals(type)){String number=required(bill,"billNo");BigDecimal open=db.sql("select coalesce(sum(case when ba.type='New Ref' then ba.amount when ba.type='Against Ref' then -ba.amount else 0 end),0) from bill_allocation ba join voucher_line vl on vl.id=ba.voucher_line_id join voucher v on v.id=vl.voucher_id where v.business_id=:b and vl.ledger_id=:l and v.status='Posted' and ba.bill_no=:n").param("b",business).param("l",ledger).param("n",number).query(BigDecimal.class).single();String key=ledger+":"+number;BigDecimal already=settlements.getOrDefault(key,BigDecimal.ZERO);if(!settlementFits(open,already,amount))throw new ApiException(HttpStatus.CONFLICT,"BILL_SETTLEMENT_EXCEEDS_OPEN","Bill settlement exceeds the open reference amount");settlements.put(key,already.add(amount));}}
  static boolean settlementFits(BigDecimal open,BigDecimal already,BigDecimal amount){return open!=null&&already!=null&&amount!=null&&already.signum()>=0&&amount.signum()>0&&already.add(amount).compareTo(open)<=0;}
  private LocalDate optionalDate(JsonNode n,String key){if(!n.hasNonNull(key)||n.get(key).asText().isBlank())return null;try{return LocalDate.parse(n.get(key).asText());}catch(DateTimeParseException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_DATE",key+" must be a valid ISO date");}}
  private String required(JsonNode n,String k){if(!n.hasNonNull(k)||n.get(k).asText().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR",k+" is required");return n.get(k).asText();}
  private UUID uuid(JsonNode n,String k){try{return UUID.fromString(required(n,k));}catch(IllegalArgumentException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_IDENTIFIER",k+" must be a valid identifier");}} private UUID uuidOrNull(JsonNode n,String k){try{return n.hasNonNull(k)&&!n.get(k).asText().isBlank()?UUID.fromString(n.get(k).asText()):null;}catch(IllegalArgumentException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_IDENTIFIER",k+" must be a valid identifier");}}
  private BigDecimal decimal(JsonNode n,String k,BigDecimal d){try{return n.hasNonNull(k)?n.get(k).decimalValue():d;}catch(ArithmeticException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_AMOUNT",k+" must be a valid number");}}private BigDecimal decimalOrNull(JsonNode n,String k){return n.hasNonNull(k)?decimal(n,k,null):null;}
  private ApiException nf(){return new ApiException(HttpStatus.NOT_FOUND,"VOUCHER_NOT_FOUND","Voucher was not found");}private void notFound(){throw nf();}
}
