package com.mathan.erp.report;

import com.mathan.erp.security.UserPrincipal;
import com.mathan.erp.tenant.TenantService;
import java.time.LocalDate;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/reports")
public class ReportController {
  private final JdbcClient db; private final TenantService tenants;
  public ReportController(JdbcClient db,TenantService tenants){this.db=db;this.tenants=tenants;}

  @GetMapping("/trial-balance") List<?> trial(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(required=false)UUID currencyId){
    UUID b=tenants.require(u,h,"reports").businessId();String d=voucherClause(from,to,currencyId,"v.voucher_date");String debitExpr=amountExpression(currencyId,"debit"),creditExpr=amountExpression(currencyId,"credit");
    return db.sql("select l.id,l.account_code,l.name,g.name group_name,g.nature,l.opening_balance,l.opening_balance_type,coalesce(sum(case when v.status='Posted' "+d+" then "+debitExpr+" else 0 end),0) debit,coalesce(sum(case when v.status='Posted' "+d+" then "+creditExpr+" else 0 end),0) credit from ledger l join account_group g on g.id=l.group_id and g.business_id=:b left join voucher_line vl on vl.ledger_id=l.id left join voucher v on v.id=vl.voucher_id and v.business_id=:b where l.business_id=:b group by l.id,g.name,g.nature order by l.account_code,l.name").param("b",b).param("fromDate",from).param("toDate",to).param("currencyId",currencyId).query((rs,n)->{
      var debit=rs.getBigDecimal("debit");var credit=rs.getBigDecimal("credit");var opening=currencyId==null?rs.getBigDecimal("opening_balance"):java.math.BigDecimal.ZERO;String nature=rs.getString("nature");String type=rs.getString("opening_balance_type");var signedOpening=("Asset".equals(nature)||"Expense".equals(nature))?(("Dr".equals(type))?opening:opening.negate()):(("Cr".equals(type))?opening:opening.negate());var row=new LinkedHashMap<String,Object>();row.put("ledgerId",rs.getObject("id",UUID.class));row.put("accountCode",rs.getString("account_code"));row.put("ledgerName",rs.getString("name"));row.put("groupName",rs.getString("group_name"));row.put("nature",nature);row.put("normalBalance",normalBalance(nature,rs.getString("account_code")));row.put("openingBalance",opening);row.put("openingBalanceType",type);row.put("debit",debit);row.put("credit",credit);row.put("closingBalance",signedOpening.add(debit).subtract(credit));return row;
    }).list();
  }
  @GetMapping("/ledger/{ledgerId}") List<?> ledger(@PathVariable UUID ledgerId,@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(required=false)UUID currencyId){UUID b=tenants.require(u,h,"reports").businessId();String d=voucherClause(from,to,currencyId,"v.voucher_date"),debitExpr=amountExpression(currencyId,"debit"),creditExpr=amountExpression(currencyId,"credit");return db.sql("select v.id,v.voucher_date,v.number,v.type,v.narration,"+debitExpr+" debit,"+creditExpr+" credit from voucher_line vl join voucher v on v.id=vl.voucher_id and v.business_id=:b join ledger l on l.id=vl.ledger_id and l.business_id=:b where vl.ledger_id=:l and v.status='Posted' "+d+" order by v.voucher_date,v.created_at").param("b",b).param("l",ledgerId).param("fromDate",from).param("toDate",to).param("currencyId",currencyId).query((rs,n)->Map.of("voucherId",rs.getObject("id",UUID.class),"date",rs.getObject("voucher_date",LocalDate.class),"number",rs.getString("number"),"type",rs.getString("type"),"narration",rs.getString("narration"),"debit",rs.getBigDecimal("debit"),"credit",rs.getBigDecimal("credit"))).list();}
  @GetMapping("/stock-summary") List<?> stock(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h,@RequestParam(required=false)LocalDate asOf,@RequestParam(required=false)LocalDate to){UUID b=tenants.require(u,h,"reports").businessId();LocalDate cutoff=asOf!=null?asOf:to;if(cutoff==null)return db.sql("select sb.product_id,p.name product_name,sb.warehouse_id,w.name warehouse_name,sb.quantity,sb.inventory_value,sb.average_cost,sb.costing_basis from stock_balance sb join product p on p.id=sb.product_id and p.business_id=:b join warehouse w on w.id=sb.warehouse_id and w.business_id=:b where sb.business_id=:b order by p.name,w.name").param("b",b).query((rs,n)->stockRow(rs.getObject("product_id",UUID.class),rs.getString("product_name"),rs.getObject("warehouse_id",UUID.class),rs.getString("warehouse_name"),rs.getBigDecimal("quantity"),rs.getBigDecimal("inventory_value"),rs.getBigDecimal("average_cost"),rs.getString("costing_basis"))).list();return db.sql("select sm.product_id,p.name product_name,sm.warehouse_id,w.name warehouse_name,coalesce(sum(sm.quantity),0) quantity,coalesce(sum(sm.cost_value),0) inventory_value from stock_movement sm join voucher v on v.id=sm.voucher_id and v.business_id=:b and v.status='Posted' and v.voucher_date<=:cutoff join product p on p.id=sm.product_id and p.business_id=:b join warehouse w on w.id=sm.warehouse_id and w.business_id=:b where sm.business_id=:b group by sm.product_id,p.name,sm.warehouse_id,w.name having sum(sm.quantity)<>0 order by p.name,w.name").param("b",b).param("cutoff",cutoff).query((rs,n)->{var quantity=rs.getBigDecimal("quantity");var value=rs.getBigDecimal("inventory_value");return stockRow(rs.getObject("product_id",UUID.class),rs.getString("product_name"),rs.getObject("warehouse_id",UUID.class),rs.getString("warehouse_name"),quantity,value,quantity.signum()==0?java.math.BigDecimal.ZERO:value.abs().divide(quantity.abs(),4,java.math.RoundingMode.HALF_UP),"MOVING_AVERAGE_COST");}).list();}
  @GetMapping("/stock-reconciliation") List<?> stockReconciliation(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h,@RequestParam(required=false)LocalDate asOf,@RequestParam(required=false)LocalDate to){UUID b=tenants.require(u,h,"reports").businessId();LocalDate cutoff=asOf!=null?asOf:to;String cutoffClause=cutoff==null?"":" and v.voucher_date<=:cutoff";return db.sql("select coalesce(sb.product_id,m.product_id) product_id,p.name product_name,coalesce(sb.warehouse_id,m.warehouse_id) warehouse_id,w.name warehouse_name,coalesce(sb.quantity,0) stored_quantity,coalesce(sb.inventory_value,0) stored_value,coalesce(m.quantity,0) movement_quantity,coalesce(m.inventory_value,0) movement_value from stock_balance sb full join (select sm.business_id,sm.product_id,sm.warehouse_id,sum(sm.quantity) quantity,sum(sm.cost_value) inventory_value from stock_movement sm join voucher v on v.id=sm.voucher_id and v.business_id=:b and v.status='Posted'"+cutoffClause+" where sm.business_id=:b group by sm.business_id,sm.product_id,sm.warehouse_id) m on m.business_id=sb.business_id and m.product_id=sb.product_id and m.warehouse_id=sb.warehouse_id join product p on p.id=coalesce(sb.product_id,m.product_id) and p.business_id=:b join warehouse w on w.id=coalesce(sb.warehouse_id,m.warehouse_id) and w.business_id=:b where coalesce(sb.business_id,m.business_id)=:b order by p.name,w.name").param("b",b).param("cutoff",cutoff).query((rs,n)->{var sq=rs.getBigDecimal("stored_quantity");var sv=rs.getBigDecimal("stored_value");var mq=rs.getBigDecimal("movement_quantity");var mv=rs.getBigDecimal("movement_value");var qv=mq.subtract(sq);var vv=mv.subtract(sv);var row=new LinkedHashMap<String,Object>();row.put("productId",rs.getObject("product_id",UUID.class));row.put("productName",rs.getString("product_name"));row.put("warehouseId",rs.getObject("warehouse_id",UUID.class));row.put("warehouseName",rs.getString("warehouse_name"));row.put("storedQuantity",sq);row.put("movementQuantity",mq);row.put("quantityVariance",qv);row.put("storedValue",sv);row.put("movementValue",mv);row.put("valueVariance",vv);row.put("comparison",cutoff==null?"CURRENT_BALANCE":"HISTORICAL_MOVEMENTS_ONLY");row.put("status",cutoff!=null?"NOT_COMPARABLE":qv.abs().compareTo(new java.math.BigDecimal("0.0001"))<=0&&vv.abs().compareTo(new java.math.BigDecimal("0.01"))<=0?"OK":"MISMATCH");return row;}).list();}
  @GetMapping("/profit-loss") List<?> profitLoss(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(required=false)UUID currencyId){return natureReport(u,h,List.of("Income","Expense"),from,to,currencyId,false);}
  @GetMapping("/balance-sheet") List<?> balanceSheet(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h,@RequestParam(required=false)LocalDate from,@RequestParam(required=false)LocalDate to,@RequestParam(required=false)UUID currencyId){return natureReport(u,h,List.of("Asset","Liability","Equity"),from,to,currencyId,true);}
  @GetMapping("/outstanding") List<?> outstanding(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h){UUID b=tenants.require(u,h,"reports").businessId();return db.sql("select vl.ledger_id,ba.bill_no,max(ba.due_date) due_date,sum(case when ba.type='New Ref' then ba.amount when ba.type='Against Ref' then -ba.amount else 0 end) balance from bill_allocation ba join voucher_line vl on vl.id=ba.voucher_line_id join voucher v on v.id=vl.voucher_id and v.business_id=:b where v.status='Posted' group by vl.ledger_id,ba.bill_no having sum(case when ba.type='New Ref' then ba.amount when ba.type='Against Ref' then -ba.amount else 0 end)<>0 order by max(ba.due_date),ba.bill_no").param("b",b).query((rs,n)->{var row=new LinkedHashMap<String,Object>();row.put("ledgerId",rs.getObject("ledger_id",UUID.class));row.put("billNo",rs.getString("bill_no"));row.put("dueDate",rs.getObject("due_date",LocalDate.class));row.put("balance",rs.getBigDecimal("balance"));return row;}).list();}
  private List<?> natureReport(UserPrincipal u,String h,List<String> natures,LocalDate from,LocalDate to,UUID currencyId,boolean includeOpening){UUID b=tenants.require(u,h,"reports").businessId();String d=voucherClause(from,to,currencyId,"v.voucher_date"),debitExpr=amountExpression(currencyId,"debit"),creditExpr=amountExpression(currencyId,"credit");String opening=includeOpening&&currencyId==null?"+case when l.opening_balance_type='Dr' then l.opening_balance else -l.opening_balance end":"";return db.sql("select g.nature,l.id,l.account_code,l.name,coalesce(sum(case when v.status='Posted' "+d+" then "+debitExpr+"-"+creditExpr+" else 0 end),0)"+opening+" balance from ledger l join account_group g on g.id=l.group_id and g.business_id=:b left join voucher_line vl on vl.ledger_id=l.id left join voucher v on v.id=vl.voucher_id and v.business_id=:b where l.business_id=:b and g.nature in (:n) group by g.nature,l.id order by g.nature,l.account_code,l.name").param("b",b).param("n",natures).param("fromDate",from).param("toDate",to).param("currencyId",currencyId).query((rs,i)->{String nature=rs.getString("nature");var raw=rs.getBigDecimal("balance");var balance=("Income".equals(nature)||"Liability".equals(nature)||"Equity".equals(nature))?raw.negate():raw;return Map.of("nature",nature,"ledgerId",rs.getObject("id",UUID.class),"accountCode",rs.getString("account_code"),"ledgerName",rs.getString("name"),"balance",balance);}).list();}
  private String amountExpression(UUID currencyId,String kind){if(currencyId==null)return "vl."+kind;String txn="vl.txn_"+kind;return "coalesce("+txn+",vl."+kind+"/nullif(v.exchange_rate,0))";}
  private String voucherClause(LocalDate from,LocalDate to,UUID currencyId,String column){String s="";if(from!=null)s+=" and "+column+">=:fromDate";if(to!=null)s+=" and "+column+"<=:toDate";if(currencyId!=null)s+=" and v.currency_id=:currencyId";return s;}
  private String normalBalance(String nature,String code){if("Asset".equals(nature)||"Expense".equals(nature))return "Dr";return "5300".equals(code)?"Dr":"Cr";}
  private Map<String,Object> stockRow(UUID productId,String productName,UUID warehouseId,String warehouseName,java.math.BigDecimal quantity,java.math.BigDecimal value,java.math.BigDecimal averageCost,String basis){var row=new LinkedHashMap<String,Object>();row.put("productId",productId);row.put("productName",productName);row.put("warehouseId",warehouseId);row.put("warehouseName",warehouseName);row.put("quantity",quantity);row.put("inventoryValue",value);row.put("averageCost",averageCost);row.put("valuationBasis",basis);return row;}
}
