package com.mathan.erp.user;

import com.fasterxml.jackson.databind.JsonNode;
import com.mathan.erp.api.ApiException;
import com.mathan.erp.security.UserPrincipal;
import com.mathan.erp.tenant.TenantService;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/users")
public class UserController {
  private static final Set<String> ROLES=Set.of("admin","supervisor","accountant","sales","storekeeper");
  private final JdbcClient db; private final TenantService tenants; private final PasswordEncoder encoder;
  public UserController(JdbcClient d,TenantService t,PasswordEncoder e){db=d;tenants=t;encoder=e;}
  @GetMapping List<?> list(@AuthenticationPrincipal UserPrincipal u,@RequestHeader("X-Business-Id")String h){UUID b=tenants.require(u,h,"users").businessId();return db.sql("select u.id,u.username,u.display_name,m.role,m.active,m.masters,m.transactions,m.reports,m.audit,m.users,m.settings from membership m join app_user u on u.id=m.user_id where m.business_id=:b order by u.display_name").param("b",b).query((rs,n)->Map.of("id",rs.getObject("id",UUID.class),"username",rs.getString("username"),"name",rs.getString("display_name"),"role",rs.getString("role"),"active",rs.getBoolean("active"),"permissions",permissions(rs))).list();}
  @PostMapping @Transactional Map<String,Object> create(@AuthenticationPrincipal UserPrincipal actor,@RequestHeader("X-Business-Id")String h,@RequestBody JsonNode r){UUID b=tenants.require(actor,h,"users").businessId();String username=r.path("username").asText(),pin=r.path("pin").asText(),role=r.path("role").asText("sales");validate(username,pin);validateRole(role);UUID id=UUID.randomUUID();db.sql("insert into app_user(id,username,display_name,pin_hash) values(:id,:u,:n,:p)").param("id",id).param("u",username).param("n",r.path("name").asText(username)).param("p",encoder.encode(pin)).update();insertMembership(id,b,r);audit(b,actor.id(),"User created",id);return Map.of("id",id,"username",username,"name",r.path("name").asText(username),"role",role,"active",true);}
  @PatchMapping("/{id}") @Transactional void update(@PathVariable UUID id,@AuthenticationPrincipal UserPrincipal actor,@RequestHeader("X-Business-Id")String h,@RequestBody JsonNode r){UUID b=tenants.require(actor,h,"users").businessId();ensureMember(id,b);protectAdmin(id,b,r);if(r.hasNonNull("name"))db.sql("update app_user set display_name=:n,updated_at=now(),version=version+1 where id=:id").param("n",r.get("name").asText()).param("id",id).update();if(r.hasNonNull("username")){String username=r.get("username").asText();if(!username.matches("[A-Za-z0-9._-]{3,80}"))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Invalid username");db.sql("update app_user set username=:n,updated_at=now(),version=version+1 where id=:id").param("n",username).param("id",id).update();}if(r.hasNonNull("pin")&&!r.get("pin").asText().isBlank()){String pin=r.get("pin").asText();if(!pin.matches("\\d{4,8}"))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","PIN must contain 4 to 8 digits");db.sql("update app_user set pin_hash=:p,updated_at=now(),version=version+1 where id=:id").param("p",encoder.encode(pin)).param("id",id).update();}JsonNode p=r.path("permissions");if(r.hasNonNull("role"))validateRole(r.get("role").asText());db.sql("update membership set role=coalesce(:r,role),active=coalesce(:active,active),masters=coalesce(:m,masters),transactions=coalesce(:t,transactions),reports=coalesce(:rp,reports),audit=coalesce(:a,audit),users=coalesce(:us,users),settings=coalesce(:s,settings) where user_id=:u and business_id=:b").param("r",r.hasNonNull("role")?r.get("role").asText():null,java.sql.Types.VARCHAR).param("active",r.has("active")?r.get("active").asBoolean():null,java.sql.Types.BOOLEAN).param("m",p.has("masters")?p.get("masters").asBoolean():null,java.sql.Types.BOOLEAN).param("t",p.has("transactions")?p.get("transactions").asBoolean():null,java.sql.Types.BOOLEAN).param("rp",p.has("reports")?p.get("reports").asBoolean():null,java.sql.Types.BOOLEAN).param("a",p.has("audit")?p.get("audit").asBoolean():null,java.sql.Types.BOOLEAN).param("us",p.has("users")?p.get("users").asBoolean():null,java.sql.Types.BOOLEAN).param("s",p.has("settings")?p.get("settings").asBoolean():null,java.sql.Types.BOOLEAN).param("u",id).param("b",b).update();audit(b,actor.id(),"User updated",id);}
  @DeleteMapping("/{id}") @Transactional void remove(@PathVariable UUID id,@AuthenticationPrincipal UserPrincipal actor,@RequestHeader("X-Business-Id")String h){UUID b=tenants.require(actor,h,"users").businessId();if(id.equals(actor.id()))throw new ApiException(HttpStatus.CONFLICT,"SELF_REMOVAL","You cannot remove your own membership");ensureMember(id,b);ensureNotLastAdmin(id,b);db.sql("delete from membership where user_id=:u and business_id=:b").param("u",id).param("b",b).update();audit(b,actor.id(),"User membership removed",id);}
  private void insertMembership(UUID id,UUID b,JsonNode r){JsonNode p=r.path("permissions");db.sql("insert into membership(user_id,business_id,role,masters,transactions,reports,audit,users,settings) values(:u,:b,:r,:m,:t,:rp,:a,:us,:s)").param("u",id).param("b",b).param("r",r.path("role").asText("sales")).param("m",p.path("masters").asBoolean()).param("t",p.path("transactions").asBoolean()).param("rp",p.path("reports").asBoolean()).param("a",p.path("audit").asBoolean()).param("us",p.path("users").asBoolean()).param("s",p.path("settings").asBoolean()).update();}
  private void protectAdmin(UUID id,UUID b,JsonNode r){String current=db.sql("select role from membership where user_id=:u and business_id=:b").param("u",id).param("b",b).query(String.class).single();boolean remainsAdmin="admin".equals(r.hasNonNull("role")?r.get("role").asText():current)&&(!r.has("active")||r.get("active").asBoolean());if("admin".equals(current)&&!remainsAdmin)ensureNotLastAdmin(id,b);}
  private void ensureNotLastAdmin(UUID id,UUID b){long admins=db.sql("select count(*) from membership where business_id=:b and role='admin' and active and user_id<>:u").param("b",b).param("u",id).query(Long.class).single();if(admins==0)throw new ApiException(HttpStatus.CONFLICT,"LAST_ADMIN","The business must retain an active administrator");}
  private void ensureMember(UUID id,UUID b){if(db.sql("select exists(select 1 from membership where user_id=:u and business_id=:b)").param("u",id).param("b",b).query(Boolean.class).single()!=Boolean.TRUE)throw new ApiException(HttpStatus.NOT_FOUND,"USER_NOT_IN_BUSINESS","User is not a member of this business");}
  private Map<String,Boolean> permissions(java.sql.ResultSet rs)throws java.sql.SQLException{return Map.of("masters",rs.getBoolean("masters"),"transactions",rs.getBoolean("transactions"),"reports",rs.getBoolean("reports"),"audit",rs.getBoolean("audit"),"users",rs.getBoolean("users"),"settings",rs.getBoolean("settings"));}
  private void validate(String username,String pin){if(username.isBlank()||!username.matches("[A-Za-z0-9._-]{3,80}")||!pin.matches("\\d{4,8}"))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","A valid username and 4 to 8 digit PIN are required");}
  private void validateRole(String role){if(!ROLES.contains(role))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_ROLE","Unsupported user role");}
  private void audit(UUID b,UUID actor,String action,UUID id){db.sql("insert into audit_log(business_id,actor_id,action,entity_type,entity_id,details) values(:b,:a,:x,'user',:id,:x)").param("b",b).param("a",actor).param("x",action).param("id",id).update();}
}
